### ISSUE TITLE
Dynamic Content

### ISSUE THREAD

**Issue by jawadrehman** [alanphoon/jquery-live-preview#2]
Is there a good way of binding it to work on dynamic content. 
Thanks

**Comment by billonas** [comment]
Is this possible to the current build. If not can you try it, i really need it!

**Comment by alanphoon** [comment]
Argh. I never go to this.  I'll see if I can work on this soon.  

In the meantime this is <strong>very</strong> dirty but you can always re-initialize the plugin *if possible* after you add your dynamic content, however, just make sure to unbind the hover/click event before you do.

Insert your dynamic content, then execute the following again like:
$(".livepreview").unbind( "hover" );
$(".livepreview").unbind( "click" );
$(".livepreview").livePreview();

**Comment by billonas** [comment]
That is great, even being dirty... Thank you very match for the quick answer...
Greetings from Greece!
