### ISSUE TITLE
Multiple livepreviews for the same page

### ISSUE THREAD

**Issue by billonas** [alanphoon/jquery-live-preview#6]
Hello alanphoon,

Thanks for the great plugin. I am asking if a can use more than one livepreviews for the same page. 
For example
$(".class1").livePreview({
			trigger: 'click',
});

$(".class2").livePreview({
                         trigger: 'click',
});

**Comment by alanphoon** [comment]
Yes you can, any specific reason to do that?   You can use data attributes to customize each link if that was the intent.  ex:

<a href="www.cnn.com" class="live-preview" data-position="right">cnn</a>
<a href="www.bbcnews.com" class="live-preview" data-position="left">bbc</a>

<script>
   $(function(){
        $('.live-preview').livePreview();
   });
<script>

This will bind livePreview to both links, with one positioning left and the other to the right.
