### ISSUE TITLE
Bottom positioning?

### ISSUE THREAD

**Issue by billonas** [alanphoon/jquery-live-preview#7]
Hello alan,

It's Bill again. Is there any easy way to have bottom positioning for the iframe; I know that you haven't implemented but is there any quick way to do it (even dirty one...)?
The bottom positioning is very important because of the fact that if a link is at the top of the page and it is clicked then the iframe goes out of the page (so part of it is not shown to the user)

**Comment by alanphoon** [comment]
You'll be glad to know, I was able to finally add the "top" and "bottom" as options for positioning.  I've committed the new changes.  Make sure to update all your files again.   I haven't fully tested, so let me know if you run into any issues.   Cheers!
